### Read all the users
#GET http://localhost:4000/users
GET http://localhost:4000/products

### Read a user by id
#GET http://localhost:4000/users/27
GET http://localhost:4000/products/adidas

###create new user 
# POST http://localhost:4000/users
# Content-Type: application/json

# {
#     "id":27,
#     "name":"Kapish",
#     "age": 20
# }
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "Studs",
    "productId" : 104,
    "brand": "adidas",
    "price": 5000
}
###update a user
# PUT http://localhost:4000/users
# Content-Type: application/json

# {
#     "id":26,
#     "name":"Rawat",
#     "age": 25
# }

PUT http://localhost:4000/products
Content-Type: application/json

{
    "name": "shoes",
    "productId" : 100,
    "brand": "adidas",
    "price": 6000
}


###Delete a user 
#DELETE http://localhost:4000/users/26
DELETE http://localhost:4000/products/103
